### ISSUE TITLE
Addition of newer projects

### ISSUE THREAD

**Issue by sahil-shubham** [metakgp/metakgp.github.io#4]
There are a lot of new projects which haven't been added to the website. A few these projects are:- 

- [gyft](https://github.com/metakgp/gyft)
- [kronos](https://github.com/metakgp/Kronos)
- [Chillzone](https://github.com/metakgp/chillzone)
- [what-slot](https://github.com/metakgp/what-slot)
- [wimp](https://github.com/metakgp/wimp)
- [erp auto login](https://github.com/metakgp/erp-auto-login)

Proper cards regarding these projects should be added and linked.

**Comment by sahil-shubham** [comment]
Hey, I would like to work on this issue.

**Comment by Ayushk4** [comment]
@thealphadollar can you assign the issue.

**Comment by thealphadollar** [comment]
@Ayushk4 Thanks for the nudge; strangely, I was not subscribed to the repository.
